version: "3"
services:
  node:
    build:
      context: ./docker/app
    ports:
      - "3011:3000"
    depends_on:
      - db
    volumes:
      - ./app:/app
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: linebot
      MYSQL_PASSWORD: linebot
      MYSQL_ROOT_PASSWORD: linebot
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_general_ci
      TZ: "Asia/Tokyo"
    volumes:
      - ./docker/db/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_USER: linebot
      MYSQL_PASSWORD: linebot
      MYSQL_ROOT_PASSWORD: linebot

  ultrahook:
    build:
      context: ./docker/ultrahook
    depends_on:
      - node
